apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "ghost.vaxly.io/v1alpha1",
          "kind": "Blog",
          "metadata": {
            "name": "vaxly-blog"
          },
          "spec": {
            "config": {
              "database": {
                "client": "mysql",
                "connection": {
                  "database": "ghostdb",
                  "host": "localhost",
                  "password": "secret",
                  "port": 3306,
                  "user": "root"
                }
              },
              "logging": {
                "transports": [
                  "stdout"
                ]
              },
              "mail": {
                "transport": "direct"
              },
              "url": "https://blog.vaxly.io"
            },
            "image": "ghost:3.40.1",
            "ingress": {
              "annotations": {
                "cert-manager.io/cluster-issuer": "letsencrypt-prod",
                "kubernetes.io/ingress.class": "nginx",
                "kubernetes.io/tls-acme": "true"
              },
              "enabled": true,
              "hosts": [
                "blog.vaxly.io"
              ],
              "tls": {
                "enabled": true,
                "secretName": "blog-vaxly-io-prod"
              }
            },
            "persistent": {
              "enabled": true,
              "size": "10Gi"
            },
            "replicas": 1,
            "serviceType": "ClusterIP"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: ghost-operator.v0.0.4
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Blog is the Schema for the blogs API
      displayName: Blog
      kind: Blog
      name: blogs.ghost.vaxly.io
      version: v1alpha1
  description: Deploy the ghost blogging platform using kubernets operator framework
  displayName: ghost-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ghost.vaxly.io
          resources:
          - blogs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ghost.vaxly.io
          resources:
          - blogs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: ghost-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: vaxlyio/ghost-operator:0.0.4
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ghost
  - operator
  - blog
  - kubernetes
  - k8s
  links:
  - name: Ghost Operator
    url: https://ghost-operator.domain
  maintainers:
  - email: vaxlyio@gmail.com
    name: vaxly
  maturity: alpha
  provider:
    name: vaxly
  version: 0.0.4
