apiVersion: ghost.vaxly.io/v1alpha1
kind: Blog
metadata:
  name: vaxly-blog
spec:
  replicas: 1
  image: ghost:3.40.1
  persistent:
    enabled: true
    size: 10Gi
  serviceType: ClusterIP
  ingress:
    enabled: true
    tls:
      enabled: true
      secretName: blog-vaxly-io-prod  # Must change
    hosts:
      - blog.vaxly.io # Must change
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod # Must change
      kubernetes.io/tls-acme: "true"
  config:
    url: https://blog.vaxly.io  # Must change
    server:
      host: 0.0.0.0
      port: 80
    mail:
      transport: direct
    logging:
      transports:
        - stdout
    database:
      client: mysql
      connection:
        host: localhost
        port: 3306
        user: root
        password: secret  # Must change
        database: ghostdb